version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pollingapp-container
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - .:/code
